name: .NET CICD

on:
  push:
    branches: 
    - master 
    - feature/*
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  
    # https://github.com/marketplace/actions/gittools
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.13
      with:
        versionSpec: '5.x'
    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.9.13
      id: gitversion
      with:
        useConfigFile: true
        configFilePath: GitVersion.yml
    - name: echo measured VERSION
      run: echo ${{ steps.gitversion.outputs.SemVer }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore 
    - name: Build
      run: dotnet build  --no-restore --configuration Release /p:Version=${{ steps.gitversion.outputs.SemVer }}
    - name: Pack
      run: dotnet pack  --no-build --configuration Release -p:PackageVersion=${{ steps.gitversion.outputs.SemVer }}
    - name: Push
      run: dotnet nuget push --source "https://nuget.pkg.github.com/unaihuete-org/index.json" --api-key ${{ secrets.PAT_GH_PACKAGES }} "**/*.nupkg"
